#pragma once
#include <string>

// SABSE BASE CLASS FOR OTHER GAMES TO INHERIT FROM.
// DEFINES THE *INTERFACE* FOR ALL GAMES IN THE CASINO.
// CONTAINS PURE UNIMPLEMENTED VIRTUAL FUNCTIONS THAT MUST BE IMPLEMENTED BY ALL DERIVED GAME CLASSES.
class Game {
public:
    // VIRTUAL DESTRUCTOR FOR PROPER CLEANUP OF DERIVED CLASSES
    virtual ~Game() = default; 

    // PURE VIRTUAL FUNCTION TO PLAY THE GAME. TAKES A REFERENCE TO THE PLAYER'S BALANCE TO MODIFY IT BASED ON WIN/LOSS.
    virtual void play(double& playerBalance) = 0; 

    // PURE VIRTUAL FUNCTION TO GET THE NAME OF THE GAME. THIS CAN BE USED FOR DISPLAY PURPOSES IN THE CASINO MANAGER.
    virtual std::string getName() const = 0;
}; 